export const type = {
  SEARCH_MOVIES: 'SEARCH_MOVIES',
  FILTER_MOVIES: 'FILTER_MOVIES',
  FILTER_SERIES: 'FILTER_SERIES',
  FILTER_TV_SHOWS: 'FILTER_TV_SHOWS',
  GET_SEARCHED_MOVIE: 'GET_SEARCHED_MOVIE',
  DELETE_SEARCH_HISTORY: 'DELETE_SEARCH_HISTORY',
};
